-- MySQL Script generated by MySQL Workbench
-- Sun Apr  8 22:43:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema toutiao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toutiao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toutiao` DEFAULT CHARACTER SET utf8 ;
USE `toutiao` ;

-- -----------------------------------------------------
-- Table `toutiao`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toutiao`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `head_image` VARCHAR(500) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `head_image_UNIQUE` (`head_image` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toutiao`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toutiao`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `news_id` INT NOT NULL,
  `content` TEXT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toutiao`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toutiao`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `main_image` VARCHAR(500) NOT NULL COMMENT 'url相对地址',
  `like_count` INT NOT NULL,
  `comment_count` INT NOT NULL,
  `content` TEXT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `main_image_UNIQUE` (`main_image` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toutiao`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toutiao`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fromid` INT NOT NULL,
  `toid` INT NOT NULL,
  `content` TEXT NULL,
  `conversation_id` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `conversation_id_index` (`conversation_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
